stages:
  - deploy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: 'us-east-1'
  STACK_NAME: 'my-cloudformation-template'

before_script:
  - apt-get update -y
  - apt-get install -y awscli unzip

deploy:
  stage: deploy
  script:
    # Check if the CloudFormation stack exists
    - |
      STACK_STATUS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].StackStatus" --output text)
      if [[ "$STACK_STATUS" == "CREATE_COMPLETE" || "$STACK_STATUS" == "UPDATE_COMPLETE" ]]; then
        echo "Stack already exists. Updating stack..."
        aws cloudformation update-stack --stack-name $STACK_NAME --template-body file://cloudformation/cloudformation-template.yaml --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
      else
        echo "Stack does not exist. Creating stack..."
        aws cloudformation create-stack --stack-name $STACK_NAME --template-body file://cloudformation/cloudformation-template.yaml --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
      fi
  only:
    - My-cloudformation-project
