version: 0.2

phases:
  install:
    commands:
      - echo Checking if AWS CLI is installed
      - aws --version || (echo "AWS CLI not found, installing..." && curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install)

  pre_build:
    commands:
      - echo Logging into AWS CLI
      - aws sts get-caller-identity

  build:
    commands:
      - echo Running build commands

  post_build:
    commands:
      - echo Deploying CloudFormation Stack
      - aws cloudformation create-stack --stack-name my-kodi2002-stack --template-body file://my-cloudformation-template.yml --capabilities CAPABILITY_NAMED_IAM
      - echo CloudFormation Stack creation initiated

artifacts:
  files:
    - '**/*'
