version: 0.2

phases:
  build:
    commands:
      - echo "This is build phase... Zipping my lambda function"
      - zip -r app.zip lambda_function.py
      - ls -al # List files to verify the zip file is created

  post_build:
    commands:
      - echo "Deploying to the Lambda"
      - aws lambda update-function-code --function-name lambda-function-demo --zip-file fileb:///app.zip

artifacts:
  type: zip
  paths:
    - '*'
