version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing AWS CLI
      - pip install awscli

  pre_build:
    commands:
      - echo Logging into AWS CLI
      - aws sts get-caller-identity # Verifies AWS CLI authentication

  build:
    commands:
      - echo Running build commands
      - # Add any other build commands (e.g., compiling code, running tests, etc.)

  post_build:
    commands:
      - echo Deploying CloudFormation Stack
      - aws cloudformation create-stack --stack-name kodi-stack --template-body file://my-cloudformation-template.yml --capabilities CAPABILITY_NAMED_IAM
      - echo CloudFormation Stack creation initiated

artifacts:
  files:
    - '**/*'
